language: java
notifications:
  email:
    - atumohan@umail.iu.edu
    - anujbhan@umail.iu.edu
jdk:
  - oraclejdk8
sudo: false
install: true
before_script:
- ./mvnw clean install -pl spring-boot-tools/spring-boot-maven-plugin -Pdefault,full
script: ./mvnw install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
